### ISSUE TITLE
Where to download BSD 100 4x and Urban 100 4x

### ISSUE THREAD

**Issue by GabrielLin** [jiny2001/deeply-recursive-cnn-tf#1]
Thank you for your project. It seems that the BSD 100 4x link in your url provided is broken and I cannot find the link your Urban 100 4x database in your link. Could you please upload to Dropbox? Thanks.

**Comment by jiny2001** [comment]
Thanks for your comment. I modified source code and data filenames. Now you can try for x3 and x4 scales, I believe.

**Comment by GabrielLin** [comment]
Thanks.
