### ISSUE TITLE
about the gpu

### ISSUE THREAD

**Issue by violetsaturn** [jiny2001/deeply-recursive-cnn-tf#12]
hi, thank you for your code! i want to try your code on gpu ,but i don not know how to add the code, Cloud you tell me where i add the code "  tf.device("/gpu:0")"?

**Comment by jiny2001** [comment]
Hi, thank you so much for trying my code.
It will automatically use your GPU if tensorflow recognize it. Thx!

**Comment by violetsaturn** [comment]
thank you for you reply ! i know it and have a try.
