### ISSUE TITLE
What are the difference between image_SRF_2 and image_SRF4?

### ISSUE THREAD

**Issue by GabrielLin** [jiny2001/deeply-recursive-cnn-tf#2]
Their resolutions are the same and their quality seem almost the same. Are image_SRF_4 is used for training scale 4x? Thanks.

**Comment by jiny2001** [comment]
Oops. SRF_2_HR and SRF_4_HR are definitely same. Originally there was some reasons for using as separated files, however, there was no reasons at all. I merged those data files and modified source code.

**Comment by GabrielLin** [comment]
Thank you for you rapid reply.
