### ISSUE TITLE
x2 scale my own photo

### ISSUE THREAD

**Issue by naseeresmael** [jiny2001/deeply-recursive-cnn-tf#4]
Hi @jiny2001 , thank you for sharing your great work , i have some  (1000 x 660 ) photos want to scale it with 2x upscal ( 2000 x 1334 ) , could you please explan to me how to get that , when i try it give me output photo with the same size for input photo .

**Comment by jiny2001** [comment]
Hi @naseeresmael , you can use do_super_resolution() function in super_resolution.py.
I added test.py for your convenience. Once you place your target image under deeply-recursive-cnn-tf directory, you can try like "python3 test.py --file your_image_filename.png". And the result will be in output directory like below.

input
![img_001](https://user-images.githubusercontent.com/12959344/30261529-e35d52f2-9681-11e7-808e-96fc380c2d4e.png)

bicubic
![img_001_bicubic](https://user-images.githubusercontent.com/12959344/30261530-e49102a4-9681-11e7-9adc-b16bc026c1bf.png)

result
![img_001_result](https://user-images.githubusercontent.com/12959344/30261531-e602fab6-9681-11e7-95d0-7c5f1bed97a9.png)

Please note when you have trained with args like "python3 main.py --inference_depth 5", you should use same args on test like "python3 test.py --inference_depth 5 --file your_file.bmp"

**Comment by jiny2001** [comment]
BTW, I got my own super resolution model after this project. That has better result and that's code is more organized. Please use this if you are interested in. 
https://github.com/jiny2001/dcscn-super-resolution

**Comment by naseeresmael** [comment]
thank you very much for your great helping, i will begin to use your own super resolution today, thanks againe for you hard work to make this work available for us.❤💛
