### ISSUE TITLE
How many feature number do you used?

### ISSUE THREAD

**Issue by GabrielLin** [jiny2001/deeply-recursive-cnn-tf#5]
As you said, 'I use half num of features (128) to make training faster for those results below.' I am a little confuse. How many of your feature number of result image shown at the page. 64, 128 or 96. Thanks.

**Comment by jiny2001** [comment]
Sorry, I wrote that explanation almost a year ago. So now it's little bit changed.
Usually I use 96 features. You can use 32, 64, 128, 256 or even more, however, in my experiments I can't get better results with using more than 128 features. It depends on other hyper parameters. You can try by yourself. :)

**Comment by jiny2001** [comment]
I mean, I recommend you to use 64 or 96 for the first. So the default is 96 in my code.
However, the table of PSNR results in the readme was calculated by 128 features.

**Comment by GabrielLin** [comment]
Your speed of reply is as fast as light. Thanks.
