### ISSUE TITLE
convert color space

### ISSUE THREAD

**Issue by chenyuyi94** [jiny2001/deeply-recursive-cnn-tf#9]
i wanna to kown, is that a trick to convert RGB space to Ycrcb space

**Comment by jiny2001** [comment]
Hi,
what are you meaning 'trick'?

I think the answer would be 'No'. Converting YCbCr and then use only Y is a quite popular technic. thx.

**Comment by chenyuyi94** [comment]
thank you for your reply.
Because of there are some abvious feature in Ycrcb space,so it is a popular technic that convert RGB space to Ycrcb space ?
I have no ideas why should convert RGB to Ycrcb.


发自我的 iPhone

**Comment by jiny2001** [comment]
Yes, it's very popular.

In YCbCr, Y is for intensity (or brightness) and other is for colors. It's said that people's eye (or brain) is more aware of intensity than colors. So it is not rare when we process on only 1 channel, we chose Y.

**Comment by jiny2001** [comment]
I'm gonna close this topic for now. Feel free to ask anything. thx.
